
COMPONENT=TestCtpAppC

CFLAGS += -I../serial-logger
CFLAGS += -I../mpdr
CFLAGS += -I../ctp
CFLAGS += -I../4bitle
CFLAGS += -I../UnicastFreeRoutingDual
CFLAGS += -I$(TOSDIR)/lib/net


include $(MAKERULES)

